// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// UsersColumns holds the columns for the "users" table.
	UsersColumns = []*schema.Column{
		{Name: "ID", Type: field.TypeInt, Increment: true},
		{Name: "USER_ID", Type: field.TypeString, Unique: true},
		{Name: "PASSWORD", Type: field.TypeString},
		{Name: "USER_NAME", Type: field.TypeString},
		{Name: "USER_STATUS", Type: field.TypeBool, Default: false},
		{Name: "EMAIL", Type: field.TypeString, Unique: true},
		{Name: "PHONE_NUMBER", Type: field.TypeString, Unique: true},
		{Name: "JOB_CODE", Type: field.TypeInt, Nullable: true},
		{Name: "PROFILE_IMAGE", Type: field.TypeString, Nullable: true},
		{Name: "GITHUB_LINK", Type: field.TypeString, Nullable: true},
		{Name: "BLOG_LINK", Type: field.TypeString, Nullable: true},
		{Name: "USER_TEXT", Type: field.TypeString, Nullable: true},
		{Name: "COMPANY", Type: field.TypeString, Nullable: true},
		{Name: "SKILL", Type: field.TypeString, Nullable: true},
		{Name: "CREATE_DATE", Type: field.TypeTime},
		{Name: "UPDATE_DATE", Type: field.TypeTime},
		{Name: "SESSION_TOKEN", Type: field.TypeString, Nullable: true},
		{Name: "SESSION_EXPIRY", Type: field.TypeTime, Nullable: true},
	}
	// UsersTable holds the schema information for the "users" table.
	UsersTable = &schema.Table{
		Name:       "users",
		Columns:    UsersColumns,
		PrimaryKey: []*schema.Column{UsersColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		UsersTable,
	}
)

func init() {
}
