// Code generated by ent, DO NOT EDIT.

package ent

import (
	"DBP/ent/schema"
	"DBP/ent/user"
	"time"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescUserId is the schema descriptor for userId field.
	userDescUserId := userFields[0].Descriptor()
	// user.UserIdValidator is a validator for the "userId" field. It is called by the builders before save.
	user.UserIdValidator = userDescUserId.Validators[0].(func(string) error)
	// userDescPassword is the schema descriptor for password field.
	userDescPassword := userFields[1].Descriptor()
	// user.PasswordValidator is a validator for the "password" field. It is called by the builders before save.
	user.PasswordValidator = userDescPassword.Validators[0].(func(string) error)
	// userDescUserName is the schema descriptor for userName field.
	userDescUserName := userFields[2].Descriptor()
	// user.UserNameValidator is a validator for the "userName" field. It is called by the builders before save.
	user.UserNameValidator = userDescUserName.Validators[0].(func(string) error)
	// userDescUserStatus is the schema descriptor for userStatus field.
	userDescUserStatus := userFields[3].Descriptor()
	// user.DefaultUserStatus holds the default value on creation for the userStatus field.
	user.DefaultUserStatus = userDescUserStatus.Default.(bool)
	// userDescPhoneNumber is the schema descriptor for phoneNumber field.
	userDescPhoneNumber := userFields[5].Descriptor()
	// user.PhoneNumberValidator is a validator for the "phoneNumber" field. It is called by the builders before save.
	user.PhoneNumberValidator = userDescPhoneNumber.Validators[0].(func(string) error)
	// userDescCreateDate is the schema descriptor for createDate field.
	userDescCreateDate := userFields[13].Descriptor()
	// user.DefaultCreateDate holds the default value on creation for the createDate field.
	user.DefaultCreateDate = userDescCreateDate.Default.(time.Time)
	// userDescUpdateDate is the schema descriptor for updateDate field.
	userDescUpdateDate := userFields[14].Descriptor()
	// user.DefaultUpdateDate holds the default value on creation for the updateDate field.
	user.DefaultUpdateDate = userDescUpdateDate.Default.(time.Time)
	// userDescIsAdmin is the schema descriptor for isAdmin field.
	userDescIsAdmin := userFields[16].Descriptor()
	// user.DefaultIsAdmin holds the default value on creation for the isAdmin field.
	user.DefaultIsAdmin = userDescIsAdmin.Default.(bool)
}
